### PR TITLE
Lazarus 2.0.1.0 + win64 + other changes

### PR DESCRIPTION
**Pull request by salvadorbs**
Hello, I used your action for my lazarus project, but I have to make some changes.

- Added Lazarus 2.0.1.0 win32
- Added Lazarus cross compile win64 in Windows (so in Windows, we can build 32bit and 64bit)
- Moved OPM packages in lazarus directory and used primaryConfig (with a directory called config in lazarus dir) in lazbuild.exe (so I can use GH action Cache and to cache only lazarus directory)
- Added param local packages (so it can add local packages in lazarus easily)
- Added param --skip-dependencies when add packages in Lazarus using lazbuild. Some packages (like BGRABitmap) have multiple .lpk and they need build in proper order (and not order as json content), so I tried add all packages with param --skip-dependencies, so when build main application, we have all necessary packages and they will build them.

Know issues:
- Checks on the optional params include-packages-opm and include-packages-local doesn't work (if they are empty strings or not)
- Bad code (mine). Duplicated code, using variables instead consts and etc... Need a refactoring.

Thank you

### CODE REVIEW

**Comment by gcarreno** [comment]
Hey @salvadorbs ,

Many thanks for your contribution. I'm not going to merge this PR immediately and these are the reasons why:

1. Last time I checked the windows virtual machines on GitHub are only 32b. If something changed, then give me a shout and I'll incorporate that.
2. The fact that dependencies are not implemented was due to me wanting to rush the Packages feature but not wanting to put the effort in to make it work. Adding skip dependencies is a short cut and I'll consider it.
3. You have included a lot of code for linting and testing that I'm not interested in adding at the moment. Before you added it on this PR I already had a look at the linting and testing and opted not to go that way, yet. Maybe in the future.
4. I haven't looked at all your commits yet and want to revise then thoroughly.
5. If I can avoid including `node_modules/*` in the versioning I'm gonna always do it. Hence the dev dependency on `@vercel/ncc`

I've added 2.0.10 as the default stable now. In a short future I'll complete the analyses of your commits and see what I'll add.

Again, many, MANY thanks for your contribution.

Cheers,
Gus

**Comment by quark-zju** [comment]
Hi @gcarreno, I can confirm Github Windows is 64-bit. Its installed software is documented in https://github.com/actions/virtual-environments/blob/win19/20210121.0/images/win/Windows2019-Readme.md and I manually confirmed that `rustup show` prints:

    Default host: x86_64-pc-windows-msvc
    rustup home:  C:\Users\runneradmin\.rustup
    stable-x86_64-pc-windows-msvc (default)
    rustc 1.49.0 (e1884a8e3 2020-12-29)

My use-case is calling Rust from Lazarus using DLLs. The rust compiler now produces 64-bit DLL, which is incompatible with 32-bit Lazarus. Could you merge or add win64 support? Thanks!

I saw a typo `satble` in `README`. It might be nice to fix by the way.

**Comment by quark-zju** [comment]
I took a bit closer look. The nodejs runtime would return `win32` for `os.platform()` on 64-bit Windows:

```
> os.platform()
'win32'
```

The name is confusing, but `os.arch()` can be used to figure out the 64-bit architecture:

```
> os.arch()
'x64'
```

**Comment by gcarreno** [comment]
Hey @quark-zju,

I see that you did a bit more investigation on this than I did, and for that i THANK YOU very much.

Building on your info, I can add params to do win32/win64 with no need for cross-compile.
And I think I can also do the same for Linux i386/x86_64. But I need a bit more time to flesh my initial thoughts out.

Nonetheless, many thanks for the `os.platform()` and `os.arch()`.

For a quick fix I'll also switch from 32b to 64b on the Windows installs so that you get a correct build.
And thanks for the README typo alert :)

Cheers,
Gus

**Comment by gcarreno** [comment]
Closing due to the fact that this PR is now out of date.

**Pull request closed without merging**
